export const handleError = (err: Error) => {
	console.error(err)
	process.exit(1)
}
